# Konfiguracija za bazu podataka
spring.datasource.url=jdbc:mysql://localhost:3306/pokrivenost
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Podesavanja za citljiv prikaz SQL output-a
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true